version: "3.8"

services:
  backend:
    build: ./backend
    container_name: tripplanner-backend
    network_mode: host
    volumes:
      - ./backend/users.db:/app/users.db

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: tripplanner-gateway
    network_mode: host
    volumes:
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
